### PR TITLE
fix crop drop

### LINKED ISSUE #8289: Cotton bushes do not break
modpack: GTNH 2.1.1.0
server: my own local server
discord server username: Peytob
Looked at past discussions and never found a message about this bug. Sorry if this is a duplicate. 
If you break the farmlands with a shovel, the cotton bushes will not break. Other plants break down normally.

bug

### PR DESCRIPTION
**Pull request by GlodBlock**
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8289
dirt? interesting

### CODE REVIEW

**Comment by D-Cysteine** [comment]
I think this will prevent growing the plants on anything that's not vanilla farmland? I think `Block.canSustainPlant` might be better:
https://github.com/GTNewHorizons/Natura/blob/3223409ece40e6782f595263d5f1ccc814d093db/src/main/java/mods/natura/items/NaturaSeeds.java#L73

**Comment by GlodBlock** [comment]
> I think this will prevent growing the plants on anything that's not vanilla farmland? I think `Block.canSustainPlant` might be better:

in fact that check is completely redundant. `BlockBush` has done these things.

**Comment by Dream-Master** [comment]
@GlodBlock @D-Cysteine Cotton grows on dirt and grass in the wild. Are this change make it impossible to grow n this blocks in world generation ?

**Comment by D-Cysteine** [comment]
Good call; I completely forgot about that. I took a look and I think we might be okay though. So it looks like there is some special case code that makes wild cotton able to stay on any block:
https://github.com/GTNewHorizons/Natura/blob/3223409ece40e6782f595263d5f1ccc814d093db/src/main/java/mods/natura/blocks/crops/CropBlock.java#L252-L254
I looked at the implementation of `BlockBush.checkAndDropBlock()` and it ends up checking `CropBlock.canBlockStay()`, so I think it should pick up that exception. Though I guess the best way to be sure is to test it and see if cotton gets generated correctly.

The actual worldgen looks like it's being done here:
https://github.com/GTNewHorizons/Natura/blob/3223409ece40e6782f595263d5f1ccc814d093db/src/main/java/mods/natura/worldgen/BaseCropWorldgen.java#L146-L148
so I think it's using the metadata value of `8` for these wild cotton plants. Looks like the wild cotton plants can generate anywhere that yellow flowers can.

**Comment by Dream-Master** [comment]
ok fine i merge this now and we check this ingame

**Review by Dream-Master — APPROVED** [review]

**Comment by Dream-Master** [comment]
Seems to work

image

**Comment by D-Cysteine** [comment]
I wasn't able to find a biome with exposed dirt, but I did find some barley and cotton on podzol too. So yeah, seems good.

**Pull request merged**
